services:
  redis:
    image: redis:7-alpine
    container_name: nuxt-cache-redis
    restart: unless-stopped
    ports:
      - "6380:6379"  # Expose Redis on port 6380 instead of default 6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    environment:
      - REDIS_REPLICATION_MODE=master
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: nuxt-cache-redis-ui
    restart: unless-stopped
    ports:
      - "8081:8081"  # Redis web UI
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis

volumes:
  redis_data:
    driver: local
